5.1.0.5 (#124) (#136)
* #101 Run message flush task later to make sure locale is correct

* #101 Tweak message flush task to 2.5s

* New Crowdin updates (#97)

* New translations messages.json (French)

* New translations messages.json (Hungarian)

* New translations messages.json (Portuguese, Brazilian)

* New translations messages.json (Vietnamese)

* New translations messages.json (English)

* New translations messages.json (Chinese Simplified)

* New translations messages.json (Ukrainian)

* New translations messages.json (Turkish)

* New translations messages.json (Serbian (Cyrillic))

* New translations messages.json (Russian)

* New translations messages.json (Portuguese)

* New translations messages.json (Polish)

* New translations messages.json (Dutch)

* New translations messages.json (Korean)

* New translations messages.json (Japanese)

* New translations messages.json (Hebrew)

* New translations messages.json (Spanish)

* New translations messages.json (Finnish)

* New translations messages.json (Greek)

* New translations messages.json (German)

* New translations messages.json (Danish)

* New translations messages.json (Czech)

* New translations messages.json (Catalan)

* New translations messages.json (Arabic)

* New translations messages.json (Afrikaans)

* New translations messages.json (Romanian)

* New translations messages.json (Thai)

* New translations messages.json (Chinese Traditional)

* New translations messages.json (Swedish)

* New translations messages.json (Norwegian)

* New translations messages.json (Italian)

* New translations messages.json (Chinese Traditional, Hong Kong)

* New translations messages.json (Chinese Simplified)

* New translations messages.json (Chinese Traditional)

* Fix override files and message broken when crowdin path broke

* Fix Signature Verify failed after reset config by /qs reset config

* Change build link

* Fix hot loading/unloading integration doesn't work

* Fix Hot Unload/load integration system again

* Update URLs in issue forms (#111)

* update URLs in issue templates

* Update performance.yml

* Update wiki_contribution.yml

* Fix FabledSkyBlock Integration (#118)

* Fix NullPointerException when ranks options is not set

* Fix NoSuchMethodError in older minecraft version

* Bump to 5.1.0.5

* Add support version for 1.18.2, no updates needed

* Fix #100 according to PR #115, thanks to @tdiant

* Update contributor

* Bump MockBukkit-v1.18 from 1.15.5 to 1.18.1 (#121)

Bumps [MockBukkit-v1.18](https://github.com/MockBukkit/MockBukkit) from 1.15.5 to 1.18.1.
- [Release notes](https://github.com/MockBukkit/MockBukkit/releases)
- [Commits](https://github.com/MockBukkit/MockBukkit/commits)

---
updated-dependencies:
- dependency-name: com.github.seeseemelk:MockBukkit-v1.18
  dependency-type: direct:development
  update-type: version-update:semver-minor
...

Signed-off-by: dependabot[bot] <support@github.com>

Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>

* Bump GriefPrevention from 16.17.1 to 16.18 (#119)

Bumps [GriefPrevention](https://github.com/TechFortress/GriefPrevention) from 16.17.1 to 16.18.
- [Release notes](https://github.com/TechFortress/GriefPrevention/releases)
- [Commits](https://github.com/TechFortress/GriefPrevention/compare/16.17.1...16.18)

---
updated-dependencies:
- dependency-name: com.github.TechFortress:GriefPrevention
  dependency-type: direct:production
  update-type: version-update:semver-minor
...

Signed-off-by: dependabot[bot] <support@github.com>

Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>

* Bump worldguard-bukkit from 7.0.6 to 7.0.7 (#122)

Bumps worldguard-bukkit from 7.0.6 to 7.0.7.

---
updated-dependencies:
- dependency-name: com.sk89q.worldguard:worldguard-bukkit
  dependency-type: direct:production
  update-type: version-update:semver-patch
...

Signed-off-by: dependabot[bot] <support@github.com>

Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>

* Bump LandsAPI from 5.25.7 to 5.27.2 (#117)

Bumps [LandsAPI](https://github.com/Angeschossen/LandsAPI) from 5.25.7 to 5.27.2.
- [Release notes](https://github.com/Angeschossen/LandsAPI/releases)
- [Commits](https://github.com/Angeschossen/LandsAPI/compare/5.25.7...5.27.2)

---
updated-dependencies:
- dependency-name: com.github.angeschossen:LandsAPI
  dependency-type: direct:production
  update-type: version-update:semver-minor
...

Signed-off-by: dependabot[bot] <support@github.com>

Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>

* Bump maven-javadoc-plugin from 3.3.1 to 3.3.2 (#104)

Bumps [maven-javadoc-plugin](https://github.com/apache/maven-javadoc-plugin) from 3.3.1 to 3.3.2.
- [Release notes](https://github.com/apache/maven-javadoc-plugin/releases)
- [Commits](https://github.com/apache/maven-javadoc-plugin/compare/maven-javadoc-plugin-3.3.1...maven-javadoc-plugin-3.3.2)

---
updated-dependencies:
- dependency-name: org.apache.maven.plugins:maven-javadoc-plugin
  dependency-type: direct:production
  update-type: version-update:semver-patch
...

Signed-off-by: dependabot[bot] <support@github.com>

Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>

* Bump maven-compiler-plugin from 3.9.0 to 3.10.0 (#105)

Bumps [maven-compiler-plugin](https://github.com/apache/maven-compiler-plugin) from 3.9.0 to 3.10.0.
- [Release notes](https://github.com/apache/maven-compiler-plugin/releases)
- [Commits](https://github.com/apache/maven-compiler-plugin/compare/maven-compiler-plugin-3.9.0...maven-compiler-plugin-3.10.0)

---
updated-dependencies:
- dependency-name: org.apache.maven.plugins:maven-compiler-plugin
  dependency-type: direct:production
  update-type: version-update:semver-minor
...

Signed-off-by: dependabot[bot] <support@github.com>

Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>

* Bump PlotSquared-Core from 6.4.0 to 6.5.1 (#114)

Bumps [PlotSquared-Core](https://github.com/IntellectualSites/PlotSquared) from 6.4.0 to 6.5.1.
- [Release notes](https://github.com/IntellectualSites/PlotSquared/releases)
- [Commits](https://github.com/IntellectualSites/PlotSquared/compare/6.4.0...6.5.1)

---
updated-dependencies:
- dependency-name: com.plotsquared:PlotSquared-Core
  dependency-type: direct:production
  update-type: version-update:semver-minor
...

Signed-off-by: dependabot[bot] <support@github.com>

Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>

* Bump SpartanAPI from 2.0 to 3.0 (#113)

Bumps SpartanAPI from 2.0 to 3.0.

---
updated-dependencies:
- dependency-name: me.vagdedes.spartan:SpartanAPI
  dependency-type: direct:production
  update-type: version-update:semver-major
...

Signed-off-by: dependabot[bot] <support@github.com>

Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>

* Create crowdin action

* Update crowdin.yml

* Update crowdin.yml

* Update crowdin.yml

* Update crowdin.yml

* Update crowdin.yml

* Fix #112, reset format after item

* Let crowdin action runs every 6 hours

* Fix RGB color not working in control panel

* Try to fix item name with big nbt creating again

* Fix VirtualDisplayItem not working in ProtocolLib 5.0.0

* Fix build

* Try to fix dupe item bug

* Fix limit not working

* Improve root command tab-completing

* Fix root command tab-completing not working

* Bump PlotSquared-Core from 6.5.1 to 6.6.0 (#127)

Bumps [PlotSquared-Core](https://github.com/IntellectualSites/PlotSquared) from 6.5.1 to 6.6.0.
- [Release notes](https://github.com/IntellectualSites/PlotSquared/releases)
- [Commits](https://github.com/IntellectualSites/PlotSquared/compare/6.5.1...6.6.0)

---
updated-dependencies:
- dependency-name: com.plotsquared:PlotSquared-Core
  dependency-type: direct:production
  update-type: version-update:semver-minor
...

Signed-off-by: dependabot[bot] <support@github.com>

Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>

* New Crowdin translations by Github Action (#123)

Co-authored-by: Crowdin Bot <support+bot@crowdin.com>

* Bump item-nbt-api-plugin from 2.9.1 to 2.9.2 (#126)

Bumps item-nbt-api-plugin from 2.9.1 to 2.9.2.

---
updated-dependencies:
- dependency-name: de.tr7zw:item-nbt-api-plugin
  dependency-type: direct:production
  update-type: version-update:semver-patch
...

Signed-off-by: dependabot[bot] <support@github.com>

Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>

* Bump GemsEconomy from 4.9.3-BCRemake-1.5 to 4.9.3-GCRemake-1.6 (#106)

Bumps GemsEconomy from 4.9.3-BCRemake-1.5 to 4.9.3-GCRemake-1.6.

---
updated-dependencies:
- dependency-name: me.xanium:GemsEconomy
  dependency-type: direct:production
  update-type: version-update:semver-patch
...

Signed-off-by: dependabot[bot] <support@github.com>

Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>

* Fix i18n file download always hanging

* Fix NPE

* Replace deprecated parse method

* Fix plugin error when NBTAPI plugin is invalid

* Disable NBTAPI support by default

* New Crowdin translations by Github Action (#129)

Co-authored-by: Crowdin Bot <support+bot@crowdin.com>

* Bump PlotSquared-Core from 6.6.0 to 6.6.1 (#130)

Bumps [PlotSquared-Core](https://github.com/IntellectualSites/PlotSquared) from 6.6.0 to 6.6.1.
- [Release notes](https://github.com/IntellectualSites/PlotSquared/releases)
- [Commits](https://github.com/IntellectualSites/PlotSquared/compare/6.6.0...6.6.1)

---
updated-dependencies:
- dependency-name: com.plotsquared:PlotSquared-Core
  dependency-type: direct:production
  update-type: version-update:semver-patch
...

Signed-off-by: dependabot[bot] <support@github.com>

Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>

* Fix #133, corrent the jenkin link

* Let swapBehavior option could be reloaded

* Fix #134, correct the jenkins link again

* Bump maven-dependency-plugin from 3.2.0 to 3.3.0 (#132)

Bumps [maven-dependency-plugin](https://github.com/apache/maven-dependency-plugin) from 3.2.0 to 3.3.0.
- [Release notes](https://github.com/apache/maven-dependency-plugin/releases)
- [Commits](https://github.com/apache/maven-dependency-plugin/compare/maven-dependency-plugin-3.2.0...maven-dependency-plugin-3.3.0)

---
updated-dependencies:
- dependency-name: org.apache.maven.plugins:maven-dependency-plugin
  dependency-type: direct:production
  update-type: version-update:semver-minor
...

Signed-off-by: dependabot[bot] <support@github.com>

Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>

* Update README.md

* Update README.md

* Bump maven-compiler-plugin from 3.10.0 to 3.10.1 (#133)

Bumps [maven-compiler-plugin](https://github.com/apache/maven-compiler-plugin) from 3.10.0 to 3.10.1.
- [Release notes](https://github.com/apache/maven-compiler-plugin/releases)
- [Commits](https://github.com/apache/maven-compiler-plugin/compare/maven-compiler-plugin-3.10.0...maven-compiler-plugin-3.10.1)

---
updated-dependencies:
- dependency-name: org.apache.maven.plugins:maven-compiler-plugin
  dependency-type: direct:production
  update-type: version-update:semver-patch
...

Signed-off-by: dependabot[bot] <support@github.com>

Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>

Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
Co-authored-by: Efe Kurban <efekurbann@gmail.com>
Co-authored-by: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
Co-authored-by: Crowdin Bot <support+bot@crowdin.com>

Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
Co-authored-by: Efe Kurban <efekurbann@gmail.com>
Co-authored-by: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
Co-authored-by: Crowdin Bot <support+bot@crowdin.com>